app:
    resource: "@AppBundle/Controller/"
    type:     annotation

default_language:
    path:      /
    defaults:
        _controller: "FrameworkBundle:Redirect:redirect"
        route: "homepage"
        permanent: true
