# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
#    parameter_name: value

services:
#    service_name:
#        class: AppBundle\Directory\ClassName
#        arguments: ["@another_service_name", "plain_value", "%parameter_name%"]
    twig.extension.intl:
        class: Twig_Extensions_Extension_Intl
        tags:
            - { name: twig.extension }
    app.twig_extension:
        class: AppBundle\Twig\TilesTracker
        public: false
        tags:
            - { name: twig.extension }
    mozillians.client:
        class: %guzzle.client.class%
        tags:
            - { name: guzzle.client }
        arguments: ['https://mozillians.org']
        calls:
            - [setDefaultOption, [query, {api-key: '%mozillians.api_key%'}]]
            - [setUserAgent, [mozilla.ch, true]]
    mozilla_reps.client:
        class: %guzzle.client.class%
        tags:
            - { name: guzzle.client }
        arguments: ['https://reps.mozilla.org']
        calls:
            - [setUserAgent, [mozilla.ch, true]]
            - [setSslVerification, [false]]
    firefox_marketplace.client:
        class: %guzzle.client.class%
        tags:
            - { name: guzzle.client }
        arguments: ['https://marketplace.firefox.com/api/v2/']
        calls:
            - [setUserAgent, [mozilla.ch, true]]

